### PR TITLE
basic changes to enable us to write new test cases for zopen

### PR DESCRIPTION
**Pull request by MikeFultonDev**
light-weight test framework that lets people independently add tests of the form zopen_check_xxx to the test suite.

Moved 'zopen_check_build' code into it's own testcase as a 'sample' and created a simple README

### CODE REVIEW

**Review by IgorTodorovskiIBM — APPROVED** [review]
nice! LGTM

**Comment by MikeFultonDev** [comment]
@HarithaIBM and @devonionteuchter i hit 'merge' too fast - i would like your review too since the 4 of us will be doing a bunch of adding of tests (and hopefully others too!)

**Comment by HarithaIBM** [comment]
Sure Mike

**Comment by DevonianTeuchter** [comment]
LGTM! 
Is there plans for a set of "standard" test functions to save each test implementing their own and being more consistent with how other test frameworks operate (or even utilise one of them like shunit2/shellspec).
 For example (and by no means exhaustively tested as on my phone!!)
"assertStringEquals() { [ -n "$1" ] && [ -n "$2 ] && [ "$1" = "$2" ] && return 0 || echo "Assert failure: Strings not equal '$1' vs '$2'" && exit 8 }"
so then a test could have 
assertStringEquals "String A" "String B"
assertStringEquals "String C" "String B"
rather than lots of boiler plate code?

**Comment by MikeFultonDev** [comment]
Makes sense. Do you want to create an include directory and put the functions there?

**Pull request merged**
