### PR TITLE
Add new zopen clean test

### PR DESCRIPTION
**Pull request by DevonianTeuchter**
Add a test for zopen clean -d and -u options.
Mocks a zopen filesystem install for a dummy package

### CODE REVIEW

**Comment by IgorTodorovskiIBM** [comment]
Now that the meta change got merged, let's /run tests

**Comment by IgorTodorovskiIBM** [comment]
@DevonianTeuchter it passed, is the kill message expected?
```
Ensuring zopen clean is available
-- testpackage-1.1 <- Removed
-- testpackage-2.2 <- Removed
-- testpackage-3.3 <- Removed
-- testpackage-4.4 <- Removed
-- testpackage-5.5 <- Removed
-- testpackage-6.6 <- Removed
-- testpackage-7.7 <- Removed
-- testpackage-8.8 <- Removed
-- testpackage-9.9 <- Removed
-- testpackage-10.10 <- Removed
-> testpackage-11.11  <- Current version
Checking removal complete
Check active version is still available
Check dangling symlinks
kill: /jenkins/PortBuild/meta/meta/bin/zopen-clean 1: 83886182: EDC5143I No such process.
PASS: /jenkins/PortBuild/meta/tests/zopen_check_clean
```

**Comment by DevonianTeuchter** [comment]
> @DevonianTeuchter the test passed, is the kill message expected?
> 
> ```
> Ensuring zopen clean is available
> -- testpackage-1.1 <- Removed
> -- testpackage-2.2 <- Removed
> -- testpackage-3.3 <- Removed
> -- testpackage-4.4 <- Removed
> -- testpackage-5.5 <- Removed
> -- testpackage-6.6 <- Removed
> -- testpackage-7.7 <- Removed
> -- testpackage-8.8 <- Removed
> -- testpackage-9.9 <- Removed
> -- testpackage-10.10 <- Removed
> -> testpackage-11.11  <- Current version
> Checking removal complete
> Check active version is still available
> Check dangling symlinks
> kill: /jenkins/PortBuild/meta/meta/bin/zopen-clean 1: 83886182: EDC5143I No such process.
> PASS: /jenkins/PortBuild/meta/tests/zopen_check_clean
> ```

No - that's a separate issue (#24 )

**Review by IgorTodorovskiIBM — APPROVED** [review]
LGTM

**Pull request merged**
